# # # Settings

# # Patches
REQ_CoreScripts_AttributeSystem = "0xAD3B24~Requiem.esp"    # The Form ID and Mod Name of the Quest that holds the 'AttributeSystem' Reference Alias.

# # Formatting
LineBreak = false                                           # Adds a line break to the first whitespace of button names composed of two or more words.

# # Colors
CurrentValueColor = 0xFF0000                                # 
UpdatedValueColor = 0x00FF00                                # Colors have to be set using hexadecimal values.
ButtonColor = 0xFFFFAA                                      #

# # # Attributes

[[Attributes]]
Attribute = "Health"
Weight = 10.0

[[Attributes.Derived]]
Attribute = "TwoHandedMod"
Weight = 5.0

[[Attributes.Derived]]
Attribute = "DamageResist"
Weight = 10.0

[[Attributes.Derived]]
Attribute = "SmithingPowerMod"
Weight = 3.0

[[Attributes.Derived]]
Attribute = "UnarmedDamage"
Weight = 10.0

[[Attributes.Extra]]
Attribute = "HealRate"
Weight = 0.1

[[Attributes.Extra]]
Attribute = "PoisonResist"
Weight = 0.5

[[Attributes]]
Attribute = "Magicka"
Weight = 10.0

[[Attributes.Derived]]
Attribute = "AlterationPowerMod"
Weight = 1.0

[[Attributes.Derived.Extra]]
Attribute = "ConjurationPowerMod"
Weight = 1.0

[[Attributes.Derived.Extra]]
Attribute = "DestructionPowerMod"
Weight = 1.0

[[Attributes.Derived.Extra]]
Attribute = "IllusionPowerMod"
Weight = 1.0

[[Attributes.Derived.Extra]]
Attribute = "RestorationPowerMod"
Weight = 1.0

[[Attributes.Derived]]
Attribute = "EnchantingPowerMod"
Weight = 3.0

[[Attributes.Derived]]
Attribute = "AbsorbChance"
Weight = 1.0

[[Attributes.Derived]]
Attribute = "ShoutRecoveryMult"
Weight = -0.05

[[Attributes.Extra]]
Attribute = "MagickaRate"
Weight = 0.1

[[Attributes.Extra]]
Attribute = "MagicResist"
Weight = 0.5

[[Attributes]]
Attribute = "Stamina"
Weight = 10.0

[[Attributes.Derived]]
Attribute = "OneHandedMod"
Weight = 5.0

[[Attributes.Derived]]
Attribute = "MarksmanMod"
Weight = 5.0

[[Attributes.Derived]]
Attribute = "SpeedMult"
Weight = 3.0

[[Attributes.Derived]]
Attribute = "AlchemyMod"
Weight = 3.0

[[Attributes.Extra]]
Attribute = "StaminaRate"
Weight = 0.1

[[Attributes.Extra]]
Attribute = "CarryWeight"
Weight = 10.0